POST http://localhost:3000/solves
Content-Type: application/json

{
    "time": 8.30
}
###

GET http://localhost:3000/solves
Content-Type: application/json
###

GET http://localhost:3000/solves/solve_id
Content-Type: application/json
###

PUT http://localhost:3000/solves/solve_id
Content-Type: application/json

{
    "time": 7.85
}
###

DELETE http://localhost:3000/solves/solve_id
Content-Type: application/json
###